### ISSUE TITLE
NPCs cannot perform scripted sequences when "scared" by molotovs.

### ISSUE THREAD

**Issue by epicplayer40** [UAVXP/LeakNet#205]
If an NPC or player throws a molotov and it explodes, any NPCs who get "scared" by the molotov's flames cannot perform scripted sequences until the fire disappears.

**Comment by UAVXP** [comment]
Do you think this is a bug? I think it was made by design

**Comment by epicplayer40** [comment]
But it ruins scripted sequences when I'm making custom maps .

**Comment by UAVXP** [comment]
You can just tick "No interruptions" or/and "Override AI" flag at scripted_sequence entity
