### ISSUE TITLE
Crash on loading d3_lab_01 from 2003 September storyline map fix

### ISSUE THREAD

**Issue by stepa2** [UAVXP/LeakNet#224]
Null pointer write in ivp/ivp_intern/ivp_core.cxx line 1127

**Comment by stepa2** [comment]
Null pointer write is a way to cause crash on assertion failture

**Comment by UAVXP** [comment]
Defining NO_MUTUAL_ENERGYDESTROY in ivp_friction.hxx fixes that, but that is bad solution

**Comment by UAVXP** [comment]
IVP_Mutual_Energizer::calc_energy_potential have some quite wrong calculations, I assume, because mutual_energizer_stack.whole_mutual_energy in IVP_Friction_Core_Pair::destroy_mutual_energy getting -nan(ind) value. Need to investigate

**Comment by UAVXP** [comment]
IVP_Mutual_Energizer::calc_energy_potential() is getting inf mass1 (rot_inertia[1])

**Comment by UAVXP** [comment]
IVP_Core::set_mass
