### ISSUE TITLE
Nodegraph Generation Making Poor Climb Node Connections

### ISSUE THREAD

**Issue by epicplayer40** [UAVXP/LeakNet#242]
When a map's node graph is being rebuilt, connections to climb nodes are able to connect vertically and through world geomitry when they certainly shouldn't be.

**Comment by epicplayer40** [comment]
Incorrect connections: [https://cdn.discordapp.com/attachments/214705020980035584/685947531716460609/compilenode2.png](url)

Correct connections: https://cdn.discordapp.com/attachments/214705020980035584/685947463219413089/compilenode1.png

**Comment by UAVXP** [comment]
This relates specifically to ain generation, not the vbsp

**Comment by UAVXP** [comment]
Maybe CAI_NetworkManager::LoadNetworkGraph()
// Load all the links to the fild
